# TODO: Content in this file can become a separated action.

name: LICENSE lint

on:
  push:
  workflow_dispatch:
    inputs:
      mod:
        description: "Check only or add description"
        required: true
        default: "check"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Check for LICENSE in each defined file
        if: ${{ github.event.inputs.name != 'add' }}
        run: npm run license:check

      - name: Add LICENSE in each defined file
        if: ${{ github.event.inputs.name == 'add' }}
        run: npm run license
